import * as ts from "typescript";
import * as path from "path";
import * as fs from "fs";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");

const PACKAGES: { name: string; entry: string; namespace: string }[] = [
  {
    name: "@timeless/reactive",
    entry: "packages/reactive/src/index.ts",
    namespace: "reactive",
  },
  {
    name: "@timeless/timeless",
    entry: "packages/timeless/src/index.ts",
    namespace: "timeless",
  },
  {
    name: "@timeless/kit",
    entry: "packages/kit/src/index.ts",
    namespace: "kit",
  },
  {
    name: "@timeless/shadcn",
    entry: "packages/shadcn/src/index.ts",
    namespace: "shadcn",
  },
  {
    name: "@timeless/icons",
    entry: "packages/icons/src/index.ts",
    namespace: "icons",
  },
  {
    name: "@timeless/ui-vm",
    entry: "packages/ui-vm/src/index.ts",
    namespace: "ui",
  },
];

const BASE_COMPILER_OPTIONS: ts.CompilerOptions = {
  target: ts.ScriptTarget.ES2020,
  allowSyntheticDefaultImports: true,
  esModuleInterop: true,
  skipLibCheck: true,
  baseUrl: ROOT,
  paths: {
    "@timeless/*": ["packages/*/src/index.ts"],
  },
};

/** Collect all value exports (non-type-only) from each package entry. */
function collectExports(): Map<string, string> {
  const exportMap = new Map<string, string>(); // name → package

  const filePaths = PACKAGES.map((p) => path.resolve(ROOT, p.entry));

  const program = ts.createProgram(filePaths, {
    ...BASE_COMPILER_OPTIONS,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
  });

  const checker = program.getTypeChecker();

  for (const pkg of PACKAGES) {
    const filePath = path.resolve(ROOT, pkg.entry);
    const sourceFile = program.getSourceFile(filePath);
    if (!sourceFile) {
      console.warn(`Warning: could not load ${filePath}`);
      continue;
    }

    const symbol = checker.getSymbolAtLocation(sourceFile);
    if (!symbol) {
      console.warn(`Warning: no symbol for ${filePath}`);
      continue;
    }

    const exports = checker.getExportsOfModule(symbol);
    for (const exp of exports) {
      const name = exp.getName();

      // Skip type-only exports
      if (isTypeOnlyExport(exp)) continue;

      // Later packages override earlier (matching UMD load order)
      exportMap.set(name, pkg.name);
    }
  }

  return exportMap;
}

function isTypeOnlyExport(symbol: ts.Symbol): boolean {
  const flags = symbol.getFlags();

  // Pure type flags (no value component)
  const typeOnlyFlags =
    ts.SymbolFlags.Interface |
    ts.SymbolFlags.TypeAlias |
    ts.SymbolFlags.TypeParameter;

  if (flags & typeOnlyFlags && !(flags & ts.SymbolFlags.Value)) {
    return true;
  }

  // Check declarations for type-only export statements
  const declarations = symbol.getDeclarations();
  if (declarations && declarations.length > 0) {
    const allTypeOnly = declarations.every((decl) => {
      if (ts.isExportSpecifier(decl)) {
        const exportDecl = decl.parent?.parent;
        if (ts.isExportDeclaration(exportDecl) && exportDecl.isTypeOnly) {
          return true;
        }
      }
      if (ts.isInterfaceDeclaration(decl)) return true;
      if (ts.isTypeAliasDeclaration(decl)) return true;
      return false;
    });
    if (allTypeOnly) return true;
  }

  return false;
}

/** Emit all package declarations into a single bundled .d.ts using outFile + AMD. */
function emitBundledDeclarations(): string {
  const filePaths = PACKAGES.map((p) => path.resolve(ROOT, p.entry));

  const program = ts.createProgram(filePaths, {
    ...BASE_COMPILER_OPTIONS,
    module: ts.ModuleKind.AMD,
    moduleResolution: ts.ModuleResolutionKind.Node10,
    declaration: true,
    emitDeclarationOnly: true,
    outFile: path.resolve(__dirname, "_bundle.js"),
    rootDir: ROOT,
  });

  let bundledDts = "";
  program.emit(
    undefined,
    (fileName, text) => {
      if (fileName.endsWith(".d.ts")) {
        bundledDts = text;
      }
    },
    undefined,
    true,
  );

  if (!bundledDts) {
    console.warn("Warning: bundled declaration emit produced no output");
  }

  return bundledDts;
}

function generate() {
  const exportMap = collectExports();
  const bundledDts = emitBundledDeclarations();

  // Group by package for readable output
  const byPackage = new Map<string, string[]>();
  for (const [name, pkg] of exportMap) {
    if (!byPackage.has(pkg)) byPackage.set(pkg, []);
    byPackage.get(pkg)!.push(name);
  }

  // Sort names within each package
  for (const names of byPackage.values()) {
    names.sort();
  }

  // Generate global.d.ts
  const dtsLines: string[] = [
    "// Auto-generated by generate.ts — do not edit manually",
    "",
    "// === Bundled package type declarations ===",
    bundledDts,
    "// === Package module aliases ===",
  ];

  dtsLines.push(
    `declare module "@timeless/types" { export * from "packages/types/src/index"; }`,
  );

  for (const pkg of PACKAGES) {
    const entryModule = pkg.entry.replace(/\.ts$/, "");
    dtsLines.push(
      `declare module "${pkg.name}" { export * from "${entryModule}"; }`,
    );
  }

  dtsLines.push("");
  dtsLines.push("// === Timeless namespace ===");
  dtsLines.push("declare const Timeless: {");
  for (const pkg of PACKAGES) {
    dtsLines.push(`  ${pkg.namespace}: typeof import("${pkg.name}");`);
  }
  dtsLines.push("  [key: string]: any;");
  dtsLines.push("};");

  dtsLines.push("");
  dtsLines.push("// === Individual globals ===");
  for (const pkg of PACKAGES) {
    const names = byPackage.get(pkg.name);
    if (!names || names.length === 0) continue;
    dtsLines.push("");
    dtsLines.push(`// ${pkg.name}`);
    for (const name of names) {
      dtsLines.push(
        `declare const ${name}: typeof import("${pkg.name}").${name};`,
      );
    }
  }
  dtsLines.push("");

  const dtsPath = path.resolve(__dirname, "global.d.ts");
  fs.writeFileSync(dtsPath, dtsLines.join("\n"), "utf-8");
  console.log(`Written ${dtsPath} (${exportMap.size} exports)`);

  // Generate eslint.js
  const eslintLines: string[] = [
    "// Auto-generated by generate.ts — do not edit manually",
    "export const globals = {",
    '  Timeless: "readonly",',
  ];
  for (const pkg of PACKAGES) {
    const names = byPackage.get(pkg.name);
    if (!names || names.length === 0) continue;
    for (const name of names) {
      eslintLines.push(`  ${name}: "readonly",`);
    }
  }
  eslintLines.push("};");
  eslintLines.push("");

  const eslintPath = path.resolve(__dirname, "eslint.js");
  fs.writeFileSync(eslintPath, eslintLines.join("\n"), "utf-8");
  console.log(`Written ${eslintPath}`);
}

generate();
