// This file is manually maintained to provide type definitions for the global UMD bundles
// generated by @timeless/base and @timeless/provider-web.

import * as TimelessCore from "@timeless/base";
import * as TimelessProviderWeb from "@timeless/provider-web";

export as namespace Timeless;
export = TimelessCore;

declare global {
  // Global variable exposed by dist/timeless.domain.umd.min.js
  const Timeless: typeof TimelessCore;
  // Global variable exposed by dist/timeless.web.umd.min.js
  const TimelessWeb: typeof TimelessProviderWeb;
}
